### ISSUE TITLE
Add a more sophisticated mechanism to link experiments

### ISSUE THREAD

**Issue by lingyun1010** [ebi-gene-expression-group/atlas-web-bulk#140]
Currently an experiment can be linked to another using the factors XML file with the filed `<alternativeView>`. Because we’ll be adding links to different types of experiment, rather than “View by...” we should change the text to to “See proteomics experiment” if the accession is of a different type than the current experiment.

E-MTAB-2836 links to E-PROT-29.

**Comment by sfexova** [comment]
Hi! Just a short comment - as discussed before with Alfonso the most straightforward way is as he suggested in this Pivotal ticket https://www.pivotaltracker.com/story/show/182178275 = basically re-purposing the <alternativeView> field already in use in factors.xml for baseline bulk experiments and that's definitely the way to go now as this is quite urgent and needs to be in the next bulk release (before the SAB) and I have already edited the relevant bulk experiments accordingly.
Just a heads-up - in case it makes a difference for the work you need to put in now for this on your end - that for a long-term solution we'll need to de-couple this from the factors.xml file because that only exist for baseline experiments but in future we want to be able to link proteomics and transcriptomics experiments of different exp type too e.g. baseline-to-differential or differential-to-differential so we need the <alternativeView> field (or a new field created specifically for this purpose) to live in a file that is universal for all types of experiments in bulk (like idf)

**Comment by lingyun1010** [comment]
If the source and destination experiment types (according to accessions) are different, show link as View by [experiment type], otherwise keep the current format.

**Comment by sfexova** [comment]
Can I suggest that in such a case (source and destination experiments are of different class by accession ie E-MTAB vs E-PROT) the link is shown as 'related <proteomics/transcriptomics> experiment' rather than as View by <sth>

**Comment by lingyun1010** [comment]
Example page: https://www.ebi.ac.uk/gxa/experiments/E-MTAB-5200/Results, https://www.ebi.ac.uk/gxa/experiments/E-MTAB-5423/Results

**Comment by ke4** [comment]
This ticket has been closed in Iteration 10, but it looks like it has not been implemented properly as it is not working as it is expected according to @sfexova .
We have to pick this up again and check what happened with the already implemented PRs.
Tasks:
- [x] Review the description of the ticket with @sfexova and modify if it is needed
- [x] Check the implemented PRs
- [x] Add a fix or additional implementation if needed

**Comment by lingyun1010** [comment]
After investigation on code and data sides, and discussion with @sfexova , we found out that the corresponding file `E-PROT-29-factors.xml` is not up to date in prod and dev servers. The issue has been handed over to the data-prod team.
